export const operatingCountryOptions = [
  "Nigeria",
  "United Kingdom",
  "United States",
] as const;

export const operatingRegionOptionsByCountry = {
  Nigeria: [
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Federal Capital Territory",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara",
  ],
  "United Kingdom": ["England", "Scotland", "Wales", "Northern Ireland"],
  "United States": [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
} as const;

export const operatingCityOptionsByRegion = {
  Abia: ["Umuahia", "Aba"],
  Adamawa: ["Yola", "Mubi"],
  "Akwa Ibom": ["Uyo", "Eket"],
  Anambra: ["Awka", "Onitsha", "Nnewi"],
  Bauchi: ["Bauchi", "Azare"],
  Bayelsa: ["Yenagoa"],
  Benue: ["Makurdi", "Gboko"],
  Borno: ["Maiduguri", "Biu"],
  "Cross River": ["Calabar", "Ikom"],
  Delta: ["Asaba", "Warri"],
  Ebonyi: ["Abakaliki"],
  Edo: ["Benin City", "Ekpoma"],
  Ekiti: ["Ado Ekiti", "Ikere"],
  Enugu: ["Enugu", "Nsukka"],
  "Federal Capital Territory": ["Abuja", "Maitama"],
  Gombe: ["Gombe", "Kaltungo"],
  Imo: ["Owerri", "Orlu"],
  Jigawa: ["Dutse", "Hadejia"],
  Kaduna: ["Kaduna", "Zaria"],
  Kano: ["Kano", "Wudil"],
  Katsina: ["Katsina", "Daura"],
  Kebbi: ["Birnin Kebbi", "Argungu"],
  Kogi: ["Lokoja", "Okene"],
  Kwara: ["Ilorin", "Offa"],
  Lagos: ["Ikeja", "Lekki", "Epe", "Badagry"],
  Nasarawa: ["Lafia", "Keffi"],
  Niger: ["Minna", "Bida"],
  Ogun: ["Abeokuta", "Ijebu Ode"],
  Ondo: ["Akure", "Ondo"],
  Osun: ["Osogbo", "Ile-Ife"],
  Oyo: ["Ibadan", "Ogbomoso"],
  Plateau: ["Jos", "Bukuru"],
  Rivers: ["Port Harcourt", "Bonny"],
  Sokoto: ["Sokoto"],
  Taraba: ["Jalingo"],
  Yobe: ["Damaturu", "Potiskum"],
  Zamfara: ["Gusau"],
  England: ["London", "Manchester", "Birmingham", "Liverpool", "Bristol"],
  Scotland: ["Edinburgh", "Glasgow", "Aberdeen", "Dundee"],
  Wales: ["Cardiff", "Swansea", "Newport"],
  "Northern Ireland": ["Belfast", "Derry", "Lisburn"],
  Alabama: ["Birmingham", "Montgomery"],
  Alaska: ["Anchorage", "Juneau"],
  Arizona: ["Phoenix", "Tucson"],
  Arkansas: ["Little Rock", "Fayetteville"],
  California: ["Los Angeles", "San Francisco", "San Diego", "Sacramento"],
  Colorado: ["Denver", "Colorado Springs"],
  Connecticut: ["Bridgeport", "Hartford"],
  Delaware: ["Wilmington", "Dover"],
  "District of Columbia": ["Washington"],
  Florida: ["Miami", "Orlando", "Tampa", "Jacksonville"],
  Georgia: ["Atlanta", "Savannah"],
  Hawaii: ["Honolulu", "Hilo"],
  Idaho: ["Boise", "Idaho Falls"],
  Illinois: ["Chicago", "Springfield"],
  Indiana: ["Indianapolis", "Fort Wayne"],
  Iowa: ["Des Moines", "Cedar Rapids"],
  Kansas: ["Wichita", "Topeka"],
  Kentucky: ["Louisville", "Lexington"],
  Louisiana: ["New Orleans", "Baton Rouge"],
  Maine: ["Portland", "Augusta"],
  Maryland: ["Baltimore", "Annapolis"],
  Massachusetts: ["Boston", "Worcester"],
  Michigan: ["Detroit", "Grand Rapids"],
  Minnesota: ["Minneapolis", "Saint Paul"],
  Mississippi: ["Jackson", "Gulfport"],
  Missouri: ["Kansas City", "St. Louis", "Jefferson City"],
  Montana: ["Billings", "Helena"],
  Nebraska: ["Omaha", "Lincoln"],
  Nevada: ["Las Vegas", "Reno", "Carson City"],
  "New Hampshire": ["Manchester", "Concord"],
  "New Jersey": ["Newark", "Jersey City", "Trenton"],
  "New Mexico": ["Albuquerque", "Santa Fe"],
  "New York": ["New York City", "Buffalo", "Albany"],
  "North Carolina": ["Charlotte", "Raleigh", "Durham"],
  "North Dakota": ["Fargo", "Bismarck"],
  Ohio: ["Columbus", "Cleveland", "Cincinnati"],
  Oklahoma: ["Oklahoma City", "Tulsa"],
  Oregon: ["Portland", "Salem", "Eugene"],
  Pennsylvania: ["Philadelphia", "Pittsburgh", "Harrisburg"],
  "Rhode Island": ["Providence"],
  "South Carolina": ["Charleston", "Columbia"],
  "South Dakota": ["Sioux Falls", "Pierre"],
  Tennessee: ["Nashville", "Memphis", "Knoxville"],
  Texas: ["Houston", "Dallas", "Austin", "San Antonio"],
  Utah: ["Salt Lake City", "Provo"],
  Vermont: ["Burlington", "Montpelier"],
  Virginia: ["Virginia Beach", "Richmond", "Arlington"],
  Washington: ["Seattle", "Spokane", "Olympia"],
  "West Virginia": ["Charleston", "Morgantown"],
  Wisconsin: ["Milwaukee", "Madison"],
  Wyoming: ["Cheyenne", "Casper"],
} as const;

export const payoutMethodOptions = [
  { value: "bank_transfer", label: "Bank transfer" },
  { value: "mobile_money", label: "Mobile money" },
] as const;

export const settlementCurrencyOptions = ["GBP", "NGN", "USD"] as const;

export const payoutScheduleOptions = [
  { value: "manual", label: "Manual release" },
  { value: "daily", label: "Daily" },
  { value: "weekly", label: "Weekly" },
] as const;
