export const operatingCountryOptions = [
  "Nigeria",
  "Cameroon",
  "Central African Republic",
  "Chad",
  "Republic of the Congo",
  "Egypt",
  "Ethiopia",
  "Gabon",
  "Ghana",
  "Guinea-Bissau",
  "Ivory Coast",
  "Kenya",
  "Malawi",
  "Rwanda",
  "Senegal",
  "South Africa",
  "Tanzania",
  "Uganda",
  "Zambia",
] as const;

export const operatingRegionOptionsByCountry: Record<string, string[]> = {
  Nigeria: [
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Federal Capital Territory",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara",
  ],
  Cameroon: ["Centre"],
  "Central African Republic": ["Bangui"],
  Chad: ["N'Djamena"],
  "Republic of the Congo": ["Brazzaville"],
  Egypt: ["Cairo"],
  Ethiopia: ["Addis Ababa"],
  Gabon: ["Estuaire"],
  Ghana: ["Greater Accra"],
  "Guinea-Bissau": ["Bissau"],
  "Ivory Coast": ["Lagunes"],
  Kenya: ["Nairobi County"],
  Malawi: ["Central Region"],
  Rwanda: ["Kigali"],
  Senegal: ["Dakar"],
  "South Africa": ["Gauteng", "Western Cape"],
  Tanzania: ["Dar es Salaam", "Arusha"],
  Uganda: ["Central Region"],
  Zambia: ["Lusaka Province"],
};

export const operatingCityOptionsByCountryRegion: Record<string, Record<string, string[]>> = {
  Nigeria: {
    Abia: ["Umuahia", "Aba"],
    Adamawa: ["Yola", "Mubi"],
    "Akwa Ibom": ["Uyo", "Eket"],
    Anambra: ["Awka", "Onitsha", "Nnewi"],
    Bauchi: ["Bauchi", "Azare"],
    Bayelsa: ["Yenagoa"],
    Benue: ["Makurdi", "Gboko"],
    Borno: ["Maiduguri", "Biu"],
    "Cross River": ["Calabar", "Ikom"],
    Delta: ["Asaba", "Warri"],
    Ebonyi: ["Abakaliki"],
    Edo: ["Benin City", "Ekpoma"],
    Ekiti: ["Ado Ekiti", "Ikere"],
    Enugu: ["Enugu", "Nsukka"],
    "Federal Capital Territory": ["Abuja", "Maitama"],
    Gombe: ["Gombe", "Kaltungo"],
    Imo: ["Owerri", "Orlu"],
    Jigawa: ["Dutse", "Hadejia"],
    Kaduna: ["Kaduna", "Zaria"],
    Kano: ["Kano", "Wudil"],
    Katsina: ["Katsina", "Daura"],
    Kebbi: ["Birnin Kebbi", "Argungu"],
    Kogi: ["Lokoja", "Okene"],
    Kwara: ["Ilorin", "Offa"],
    Lagos: ["Ikeja", "Lekki", "Epe", "Badagry"],
    Nasarawa: ["Lafia", "Keffi"],
    Niger: ["Minna", "Bida"],
    Ogun: ["Abeokuta", "Ijebu Ode"],
    Ondo: ["Akure", "Ondo"],
    Osun: ["Osogbo", "Ile-Ife"],
    Oyo: ["Ibadan", "Ogbomoso"],
    Plateau: ["Jos", "Bukuru"],
    Rivers: ["Port Harcourt", "Bonny"],
    Sokoto: ["Sokoto"],
    Taraba: ["Jalingo"],
    Yobe: ["Damaturu", "Potiskum"],
    Zamfara: ["Gusau"],
  },
  Cameroon: { Centre: ["Yaounde", "Douala"] },
  "Central African Republic": { Bangui: ["Bangui"] },
  Chad: { "N'Djamena": ["N'Djamena"] },
  "Republic of the Congo": { Brazzaville: ["Brazzaville", "Pointe-Noire"] },
  Egypt: { Cairo: ["Cairo", "Alexandria"] },
  Ethiopia: { "Addis Ababa": ["Addis Ababa"] },
  Gabon: { Estuaire: ["Libreville"] },
  Ghana: { "Greater Accra": ["Accra", "Tema"] },
  "Guinea-Bissau": { Bissau: ["Bissau"] },
  "Ivory Coast": { Lagunes: ["Abidjan"] },
  Kenya: { "Nairobi County": ["Nairobi", "Mombasa"] },
  Malawi: { "Central Region": ["Lilongwe", "Blantyre"] },
  Rwanda: { Kigali: ["Kigali"] },
  Senegal: { Dakar: ["Dakar"] },
  "South Africa": { Gauteng: ["Johannesburg", "Pretoria"], "Western Cape": ["Cape Town"] },
  Tanzania: { "Dar es Salaam": ["Dar es Salaam"], Arusha: ["Arusha"] },
  Uganda: { "Central Region": ["Kampala"] },
  Zambia: { "Lusaka Province": ["Lusaka"] },
};

const uniqueSorted = (values: string[]) => [...new Set(values)].sort((a, b) => a.localeCompare(b));

export const mergeUniqueOptions = (...groups: string[][]) => {
  const merged = groups.flatMap((group) => group.filter((entry) => entry.trim().length > 0));
  return [...new Set(merged)];
};

export const localityOptionsByCountry = Object.fromEntries(
  operatingCountryOptions.map((country) => {
    const regions = [...(operatingRegionOptionsByCountry[country] ?? [])];
    const cities = regions.flatMap((region) => [...(operatingCityOptionsByCountryRegion[country]?.[region] ?? [])]);
    return [country, uniqueSorted([...regions, ...cities])];
  }),
) as Record<(typeof operatingCountryOptions)[number], string[]>;

export const payoutMethodOptions = [
  { value: "bank_transfer", label: "Bank transfer" },
  { value: "mobile_money", label: "Mobile money" },
] as const;

export const settlementCurrencyOptions = ["GBP", "NGN", "USD"] as const;

export const payoutScheduleOptions = [
  { value: "manual", label: "Manual release" },
  { value: "daily", label: "Daily" },
  { value: "weekly", label: "Weekly" },
] as const;
